# Generated by Django 5.0 on 2024-01-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='nit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
