# Generated by Django 5.0 on 2024-01-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentType',
            field=models.CharField(max_length=255),
        ),
    ]
