# Generated by Django 5.0 on 2024-01-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentType',
            field=models.CharField(choices=[('CARD', 'card'), ('CASH', 'cash')], max_length=255),
        ),
    ]
