# Generated by Django 5.0 on 2024-01-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='propina',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
