# Generated by Django 5.0.1 on 2024-01-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
