# Generated by Django 5.0 on 2024-01-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_area_name'),
        ('tables', '0002_alter_table_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'area')},
        ),
    ]
