# Generated by Django 5.0 on 2024-01-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_number_alter_table_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
    ]
