# Generated by Django 5.0 on 2024-01-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='observations',
            field=models.CharField(default='', max_length=255),
        ),
    ]
