# Generated by Django 5.0 on 2024-01-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
