# Generated by Django 5.0.1 on 2024-02-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_type_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('FOOD', 'food'), ('DRINK', 'drink')], max_length=255),
        ),
    ]
